### ISSUE TITLE
What does `C` in RelVarC mean?

### ISSUE THREAD

**Issue by YuMingLiao** [matchwood/project-m36-typed#2]
@matchwood Thanks for this great project! I learned a lot about type-level programming from this project.

Just some question pops when I study your code: What does `C` in RelVarC mean? And what is RelVarC for?

**Comment by matchwood** [comment]
If I had answered this at the time I might have had a chance of remembering! My guess is that the `C` refers to capturing the constraints in the data constructors so you can use them later. I think it was part of trying to find an interface for interaction but it ended up not being used by the look of it.
